CREATE TABLE CLIENT(
  CLI_NUM  VARCHAR2(100) PRIMARY KEY, --사업지번호
  EMP_CODE VARCHAR2(10), -- 사원코드
  CLI_NAME VARCHAR2(100) NOT NULL,-- 거래처명
  CLI_ADDR VARCHAR2(500) NOT NULL,--거래처 위치
  CLI_TEL  VARCHAR2(20) NOT NULL, -- 거래처 전화번호
  CLI_AREA VARCHAR2(20) NOT NULL, -- 거래처 지역
  CLI_USE  VARCHAR2(5) NOT NULL,-- 거래처 Y OR N
  CONSTRAINT "CLIENT_USER_FK" FOREIGN KEY ("EMP_CODE") REFERENCES USER_INFO("EMP_CODE")
);

ALTER TABLE CLIENT ADD CLI_USE VARCHAR2(5) DEFAULT 'Y';

SELECT * FROM CLIENT;

DROP TABLE CLIENT;


INSERT INTO CLIENT
(CLI_NUM, EMP_CODE, CLI_NAME, CLI_ADDR, CLI_TEL,CLI_AREA,CLI_USE)
VALUES('999-99-99999', 'CAD_23156', '카페이름', '카페상세주소', '거래처 전화번호','부산','Y');
SELECT * FROM CLIENT;


--(일반) 거래처 정보 전체 조회
SELECT CLI_NUM, EMP_CODE, CLI_NAME, CLI_ADDR, CLI_TEL, CLI_AREA
 	FROM CLIENT ;
 
--(일반) 거래처 정보 전체 조회
SELECT c2.CLI_NUM, 
	c2.EMP_CODE, 
	c2.CLI_NAME, 
	c2.CLI_ADDR, 
	c2.CLI_TEL,
	c2.CLI_AREA,
	c.CT_START,
	c.CT_END,
CASE WHEN TO_DATE(CT_START,'YYYY-MM-DD') > TO_DATE(SYSDATE,'YYYY-MM-DD')
       THEN '대기'
     WHEN TO_DATE(CT_END,'YYYY-MM-DD') < TO_DATE(SYSDATE,'YYYY-MM-DD')
       THEN '종료'
            ELSE '진행'
       END AS STATUS,
TRUNC(TO_NUMBER(TO_CHAR(TO_DATE(CT_END,'yyyy-mm-dd')-TO_DATE(CT_START,'yyyy-mm-dd')))/365) CT_DATE_YEAR_SUM
  FROM CONTRACT c 
    JOIN CONTRACT_MANAGEMENT cm 
    ON c.CTM_CODE = cm.CTM_CODE
     JOIN CLIENT c2 
    ON c2.CLI_NUM = cm.CLI_NUM;
 		
	 
--(일반) 거래처 상세조회 -> 계약 내용 포함
SELECT c.CLI_NUM, c.EMP_CODE, c.CLI_NAME, c.CLI_ADDR, c.CLI_TEL,cd.RATE,cg.G_NAME,gd.RATE AS G_CODE, cg.DU_CNT,
 CASE WHEN SYSDATE > c2.CT_START AND SYSDATE <c2.CT_END THEN '진행중' 
 WHEN SYSDATE < c2.CT_START THEN '대기중'
 WHEN SYSDATE > c2.CT_END THEN '종료'
 END AS STATUS,TRUNC(TO_NUMBER(TO_CHAR(TO_DATE(CT_END,'yyyy-mm-dd')-TO_DATE(CT_START,'yyyy-mm-dd')))/365) CT_DATE_YEAR_SUM, c2.CT_START ,c2.CT_END
	FROM CLIENT c
		JOIN CONTRACT_MANAGEMENT cm 
		ON c.CLI_NUM = cm.CLI_NUM 
	    JOIN CONTRACT c2 
	    ON c2.CTM_CODE =cm.CTM_CODE 
		JOIN CLIENT_DISCOUNT cd 
		ON c2.DCODE_CLIENT = cd.DCODE_CLIENT 
		JOIN CONTRACT_GOODS cg 
		ON c2.CT_CODE = cg.CT_CODE 
		JOIN INVENTORY_GOODS ig 
		ON cg.G_CODE = ig.G_CODE 
		JOIN GOODS_DISCOUNT gd 
		ON ig.DCODE_GOODS = gd.DCODE_GOODS
		WHERE c.CLI_NUM='200-27-93154'
		ORDER BY gd.RATE DESC;
  		   
--(일반) 거래처 정보 삭제 (delflag동작)
	UPDATE CLIENT SET CLI_USE ='N' 
	WHERE CLI_NUM='380-75-10619';

--(일반) 거래처 정보 수정
UPDATE CLIENT SET CLI_TEL ='02-623-2112', CLI_ADDR='서울특별시 관악구 낙성대역길 35, 1층 (봉천동)' WHERE CLI_NUM = '380-75-10619';

-- 

--(일반) 거래처 업체명으로 검색
SELECT CLI_NUM, EMP_CODE, CLI_NAME, CLI_ADDR, CLI_TEL, CLI_AREA
	FROM CLIENT
		WHERE CLI_NAME LIKE '%소소한%';
	


	
	
	

-- 계약서 추가 시 TRIGGER 
SELECT 
FROM CLIENT;

--거래처 등록 ( 사업자번호, 사원코드(세션에가져와야함), 거래처명... )
INSERT INTO CLIENT
(CLI_NUM, EMP_CODE, CLI_NAME, CLI_ADDR, CLI_TEL,CLI_AREA,CLI_USE)
VALUES('999-99-99999', 'CAD_23156', '카페이름', '카페상세주소', '거래처 전화번호','부산','Y');
SELECT * FROM CLIENT;


--계약관리 등록 (계약관리번호, 사업자번호 )
INSERT INTO CONTRACT_MANAGEMENT
(CTM_CODE, CLI_NUM)
VALUES('CM'||TO_CHAR(2403+CONTRACT_MANAGEMENT_SEQ.NEXTVAL), '999-99-99999');

--계약 등록 (계약번호 자동생성, 계약관리번호, 거래처할인코드는 무족건 C01 넣어준다, 납품원가도 무족건, 납품원가 입력 )
INSERT INTO CONTRACT
(CT_CODE, CTM_CODE, DCODE_CLIENT, DU_PRICE, DU_DATE, CT_START, CT_END)
VALUES(11438+CONTRACT_SEQ.NEXTVAL, 'CM'||TO_CHAR(2403+CONTRACT_MANAGEMENT_SEQ.CURRVAL), 'C01', 0, '2022-06-26', '2022-05-26', '2025-05-26');




--계약상품등록
INSERT INTO CONTRACT_GOODS
(SEQ, CT_CODE, G_CODE, G_NAME, G_PRICE, DU_CNT)
VALUES(33074+CONTRACT_GOODS_SEQ.NEXTVAL, 11438+CONTRACT_SEQ.CURRVAL,
'D010', '케냐AA', 20000, 10);

--계약 상품 합계 계산
SELECT CT_CODE, SUM(G_PRICE * DU_CNT) FROM contract_goods
GROUP BY CT_CODE
ORDER BY 1;

--상품정보조회
SELECT G_NAME, G_CODE FROM inventory_goods ;



-- 이건 이인환님께서 재고 페이지에서 등록 및 수정해야함
--재고상품 업데이트(기존쿼리 재고 업데이트 쿼리 실행)
UPDATE INVENTORY_GOODS SET IV_CNT=IV_CNT+10 WHERE G_CODE='D010'

--재고관리 등록
SELECT * FROM INVENTORY_MANAGEMENT im ORDER BY SEQ DESC;
INSERT INTO ADMIN.INVENTORY_MANAGEMENT
(SEQ, EMP_CODE, G_CODE, G_NAME, IN_DATE, IN_CNT)
VALUES(33074+INVENMANAGE_SEQ.NEXTVAL, 'IAD_13397', 'D010', '케냐AA', '2022-06-26', 10);
	


CREATE TABLE CONTRACT_GOODS AS
			SELECT * FROM CONTRACT_GOODS;
		
SELECT * FROM CONTRACT_GOODS;
SELECT *FROM CLIENT c ;




   
  























