CREATE TABLE USER_INFO(
	EMP_CODE VARCHAR2(10) PRIMARY KEY,
	AREA_CODE VARCHAR2(10),
	EMP_NAME VARCHAR2(10) NOT NULL,
	EMP_PW VARCHAR2(200) NOT NULL,
	EMP_GENDER VARCHAR2(6) NOT NULL,
	EMP_USE VARCHAR2(2) NOT NULL,
	EMP_IMG VARCHAR2(4000),
	EMP_AUTH VARCHAR2(20) NOT NULL,
	EMP_TEL VARCHAR2(20) NOT NULL,
	EMP_ADDR VARCHAR2(1000),
	CONSTRAINT "USER_INFO_FK" FOREIGN KEY ("AREA_CODE") REFERENCES LOCATION("AREA_CODE")
);

ALTER TABLE USER_INFO ADD EMP_TEL VARCHAR2(20);
ALTER TABLE USER_INFO ADD EMP_ADDR VARCHAR2(1000);
ALTER TABLE USER_INFO ADD emp_img VARCHAR2(4000);
DROP TABLE USER_INFO ;
SELECT u.EMP_NAME,
u.EMP_AUTH ,
u.EMP_CODE, u.EMP_GENDER, u.EMP_USE, u.EMP_TEL
FROM USER_INFO u
LEFT JOIN LOCATION l 
ON u.AREA_CODE= l.AREA_CODE;

SELECT * FROM board;
DROP TABLE USER_INFO;

INSERT INTO ADMIN.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG, EMP_AUTH, EMP_TEL)
VALUES('SYS_45282', NULL, '노수빈', 'subin1234', '여자', 'Y', null, 'SYSTEM', '010123456789');

INSERT INTO ADMIN.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG, EMP_AUTH, EMP_TEL)
VALUES('CAD_33873', 'LC01', '이인환', '1234', '남자', 'Y', null, 'CL_ADMIN', '01033097483');

INSERT INTO ADMIN.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG, EMP_AUTH, EMP_TEL)
VALUES('CAD_23156', 'LC04', '정상수', 'sangsoo1234', '남자', 'Y', null, 'CL_ADMIN', '01012345678');

INSERT INTO ADMIN.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG, EMP_AUTH, EMP_TEL)
VALUES('CAD_71542', 'LC02', '김대규', 'deakyu1234', '여자', 'Y', null, 'CL_ADMIN', '01012345678');

INSERT INTO ADMIN.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG, EMP_AUTH, EMP_TEL)
VALUES('CAD_98374', 'LC05', '강동원', 'dongwon1234', '남자', 'Y', null, 'CL_ADMIN', '01012345678');

INSERT INTO ADMIN.USER_INFO
(EMP_CODE, AREA_CODE, EMP_NAME, EMP_PW, EMP_GENDER, EMP_USE, EMP_IMG, EMP_AUTH, EMP_TEL)
VALUES('IAD_13397', null, '김지수', 'jisoo1234', '여자', 'Y', null, 'IV_ADMIN', '01012345678');



