SELECT 
	SEQ, 
	EMP_CODE, 
	TITLE, 
	CONTENT, 
	IMPORTANT, 
	STARTDATE, 
	ENDDATE, 
	S_COUNT, 
	POST_USE
	FROM BOARD
 	WHERE POST_USE ='Y'
 	AND
 	TO_DATE(SYSDATE, 'YYYY-MM-DD') >= TO_DATE(STARTDATE, 'YYYY-MM-DD')